In [ ]:
import requests #for get request
import pandas as pd #pandas
import numpy as np #module
import re #regex
from datetime import datetime #datetime objects
from bs4 import BeautifulSoup #prettify's our content
import json #needed for google API
import os #needed for file reading
import gmaps #for our heatmaps
import gmaps.datasets
import matplotlib.pyplot as plt #for plotting
from sklearn import linear_model #for linear regression
from sklearn.preprocessing import PolynomialFeatures #polynomial regression

In [20]:
year = 2025
months = ['01','02','03','04','05','06','07','08','09','10','11','12']
# SCRAPE EVERY MONTHS DATA
df_lst = [] # LST OF EACH MONTHS DATA
for month in months:
    req = requests.get(f"https://umpd.umd.edu/statistics-reports/daily-crime-and-incident-logs/{year}/{month}") #GET REQUEST
    print(f"Month {month} - Status Code: {req.status_code}")
    
    if req.status_code != 200:
        print(f"Failed to retrieve data for month {month}")
        continue
    
    chicken_soup = BeautifulSoup(req.content, "html.parser")
    table_list = str(chicken_soup.find("table")) #FIND THE TABLE
    
    if table_list == 'None':
        print(f"No table found for month {month}")
        continue
    
    try:
        df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST
    except ValueError as e:
        print(f"Error parsing table for month {month}: {e}")
        continue

if df_lst:
    df = pd.concat(df_lst) #CONCATENATE ALL THE DFs IN THE LIST INTO ONE LARGE DF
    df.head()
else:
    print("No data was successfully scraped")

Month 01 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 02 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 03 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 04 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 05 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 06 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 07 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 08 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 09 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 10 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 11 - Status Code: 200

C:\Users\ateeq\AppData\Local\Temp\ipykernel_11624\1510819264.py:21: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_lst.append(pd.read_html(table_list, flavor='html5lib',header=0)[0]) #CREATE AND APPEND THE DF FOR THE CURR MONTH TO THE DF_LIST

Month 12 - Status Code: 200
No table found for month 12

In [21]:
df.head()

,UMPD Case Number,Date Occurred,Report Date,Crime Type,Disposition,Unnamed: 5
0,2025-00000044,01/01/2025 01:10:00,01/01/2025 - 01:10,DWI/DUI,Arrest,NaN
1,2025-00000044,Adelphi Rd,Adelphi Rd,Adelphi Rd,Adelphi Rd,Adelphi Rd
2,2025-00000055,01/01/2025 01:48:00,01/01/2025 - 01:48,DWI/DUI,Arrest,NaN
3,2025-00000055,University Blvd,University Blvd,University Blvd,University Blvd,University Blvd
4,2025-00000056,01/01/2025 01:49:00,01/01/2025 - 01:49,Assist Other Agency,CBE,NaN

In [ ]:
# after concatenating all months
ADDRESS_COL = "Unnamed: 5"

df = df.reset_index(drop=True)
df["LOCATION"] = ""

for idx in range(1, len(df), 2):  # the rows that hold only the address
    df.at[idx - 1, "LOCATION"] = df.at[idx, ADDRESS_COL]

df = df.iloc[::2].reset_index(drop=True)
df = df.drop(columns=[ADDRESS_COL])

In [ ]:
df.head()

,UMPD Case Number,Date Occurred,Report Date,Crime Type,Disposition,LOCATION
0,2025-00000044,01/01/2025 01:10:00,01/01/2025 - 01:10,DWI/DUI,Arrest,Adelphi Rd
1,2025-00000055,01/01/2025 01:48:00,01/01/2025 - 01:48,DWI/DUI,Arrest,University Blvd
2,2025-00000056,01/01/2025 01:49:00,01/01/2025 - 01:49,Assist Other Agency,CBE,7500 block of Girard Ave
3,2025-00000083,12/29/2024 21:00:00,01/01/2025 - 03:41,Dept Property Damage/Loss,CBE,7500 block of Baltimore Ave
4,2025-00000128,01/01/2025 05:45:00,01/01/2025 - 05:45,DWI/DUI,Arrest,Adelphi Rd

In [25]:
df.to_csv(f"crime_data_{year}.csv", index=False) #EXPORT TO CSV

In [27]:
df["Crime Type"].value_counts()

Crime Type
Injured/Sick Person               357
Theft                             260
DWI/DUI                           148
Assist Other Agency               139
Other Incident                     94
Emergency Petition                 73
Vandalism                          54
Suspicious Activity                49
Damage to State Property           36
Alcohol Violation                  32
CDS Violation                      29
Warrant/Summons Service            27
Suspicious Person/Auto             22
Trespassing                        21
Dept Property Damage/Loss          21
Disorderly Conduct                 16
Assault                            16
Fire                               16
Fraud                              15
Accident                           14
Lost Property                      13
Burglary                           13
Recovered Stolen Property          13
Theft from Auto                    13
Check on the Welfare               12
Title IX Incident Non Criminal     10
Alarm                               9
Extortion                           9
Stolen Motor Vehicle                9
Hazardous Condition                 9
Damaged Property                    8
Accident - Departmental             8
Injured Officer                     8
Recovered Stolen Motor Vehicle      8
Threat Assessment                   7
Sex Offense                         7
Domestic                            7
Hate Bias Incident                  7
Found/Recovered Property            6
Telephone/EMail Misuse              5
Harassment/Stalking                 5
Pedestrian Struck                   4
Vehicle Tampering                   4
Indecent Exposure                   4
Police Information                  4
Peeping Tom                         3
Noise Complaint                     3
Identity Theft                      3
Rape                                3
Traffic Offense                     2
Weapon Violation                    2
Missing Person/Runaway              2
Traffic Arrest                      1
Reckless Endangerment               1
Robbery                             1
Name: count, dtype: int64

In [28]:
# 1. Mapping from Crime Type -> 5 broad categories
crime_category_map = {
    # 1) Violent & Person-Related
    "Injured/Sick Person": "Violent/Person-Related",
    "Injured Officer": "Violent/Person-Related",
    "Assault": "Violent/Person-Related",
    "Domestic": "Violent/Person-Related",
    "Hate Bias Incident": "Violent/Person-Related",
    "Harassment/Stalking": "Violent/Person-Related",
    "Indecent Exposure": "Violent/Person-Related",
    "Peeping Tom": "Violent/Person-Related",
    "Pedestrian Struck": "Violent/Person-Related",
    "Rape": "Violent/Person-Related",
    "Sex Offense": "Violent/Person-Related",
    "Robbery": "Violent/Person-Related",
    "Threat Assessment": "Violent/Person-Related",
    "Missing Person/Runaway": "Violent/Person-Related",
    "Check on the Welfare": "Violent/Person-Related",

    # 2) Property Crimes & Theft
    "Theft": "Property",
    "Theft from Auto": "Property",
    "Burglary": "Property",
    "Stolen Motor Vehicle": "Property",
    "Recovered Stolen Property": "Property",
    "Recovered Stolen Motor Vehicle": "Property",
    "Identity Theft": "Property",
    "Fraud": "Property",
    "Vehicle Tampering": "Property",
    "Vandalism": "Property",
    "Dept Property Damage/Loss": "Property",
    "Damage to State Property": "Property",
    "Damaged Property": "Property",
    "Lost Property": "Property",
    "Found/Recovered Property": "Property",

    # 3) Drug, Alcohol & Impairment
    "DWI/DUI": "Substance/Impairment",
    "Alcohol Violation": "Substance/Impairment",
    "CDS Violation": "Substance/Impairment",
    "Disorderly Conduct": "Substance/Impairment",
    "Reckless Endangerment": "Substance/Impairment",

    # 4) Public Safety / Suspicious / Assistive
    "Assist Other Agency": "Public Safety/Suspicious",
    "Other Incident": "Public Safety/Suspicious",
    "Suspicious Activity": "Public Safety/Suspicious",
    "Suspicious Person/Auto": "Public Safety/Suspicious",
    "Trespassing": "Public Safety/Suspicious",
    "Fire": "Public Safety/Suspicious",
    "Hazardous Condition": "Public Safety/Suspicious",
    "Accident": "Public Safety/Suspicious",
    "Accident - Departmental": "Public Safety/Suspicious",
    "Alarm": "Public Safety/Suspicious",
    "Noise Complaint": "Public Safety/Suspicious",
    "Police Information": "Public Safety/Suspicious",
    "Emergency Petition": "Public Safety/Suspicious",

    # 5) Administrative, Legal & Special
    "Warrant/Summons Service": "Admin/Legal/Special",
    "Title IX Incident Non Criminal": "Admin/Legal/Special",
    "Extortion": "Admin/Legal/Special",
    "Traffic Offense": "Admin/Legal/Special",
    "Traffic Arrest": "Admin/Legal/Special",
    "Weapon Violation": "Admin/Legal/Special",
    "Telephone/EMail Misuse": "Admin/Legal/Special",
}

# 2. Apply to your dataframe (assumes column is named exactly "Crime Type")
df["Crime_Category"] = df["Crime Type"].map(crime_category_map)

# (Optional) if you want a fallback label for anything not in the map:
df["Crime_Category"] = df["Crime_Category"].fillna("Other/Uncategorized")

# 3. Check category counts
print(df["Crime_Category"].value_counts())

Crime_Category
Property                    476
Public Safety/Suspicious    461
Violent/Person-Related      443
Substance/Impairment        226
Admin/Legal/Special          56
Name: count, dtype: int64

In [29]:
df.head()

,UMPD Case Number,Date Occurred,Report Date,Crime Type,Disposition,LOCATION,Crime_Category
0,2025-00000044,01/01/2025 01:10:00,01/01/2025 - 01:10,DWI/DUI,Arrest,Adelphi Rd,Substance/Impairment
1,2025-00000055,01/01/2025 01:48:00,01/01/2025 - 01:48,DWI/DUI,Arrest,University Blvd,Substance/Impairment
2,2025-00000056,01/01/2025 01:49:00,01/01/2025 - 01:49,Assist Other Agency,CBE,7500 block of Girard Ave,Public Safety/Suspicious
3,2025-00000083,12/29/2024 21:00:00,01/01/2025 - 03:41,Dept Property Damage/Loss,CBE,7500 block of Baltimore Ave,Property
4,2025-00000128,01/01/2025 05:45:00,01/01/2025 - 05:45,DWI/DUI,Arrest,Adelphi Rd,Substance/Impairment

In [39]:
import os
import json
import time
import pandas as pd
import requests
from dotenv import load_dotenv

# ---------- LOAD .env ----------
load_dotenv()

# Try either GOOGLE_MAPS_API_KEY or GOOGLE_API_KEY from your .env
GEOCODING_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY") 

if GEOCODING_API_KEY is None:
    raise ValueError(
        "No Geocoding API key found. Set GOOGLE_MAPS_API_KEY or GOOGLE_API_KEY in your .env file."
    )

# ---------- GOOGLE GEOCODING HELPER ----------
def geocode_with_google(location: str):
    """
    Use Google Geocoding API to get (lat, lng) for a location string.
    Returns (lat, lng) or (None, None) if it fails.
    """
    if not isinstance(location, str) or not location.strip():
        return None, None

    # Optional: bias the search around College Park, MD
    # so vague strings like "Stamp Student Union" still resolve nicely
    address = f"{location}, College Park, MD"

    url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        "address": address,
        "key": GEOCODING_API_KEY,
    }

    try:
        resp = requests.get(url, params=params)
        resp.raise_for_status()
        data = resp.json()

        if data.get("status") != "OK" or not data.get("results"):
            print(f"Geocoding failed for '{location}': {data.get('status')}")
            return None, None

        loc_data = data["results"][0]["geometry"]["location"]
        lat = loc_data.get("lat")
        lng = loc_data.get("lng")
        return lat, lng

    except Exception as e:
        print(f"Geocoding failed for '{location}': {e}")
        return None, None


# ---------- APPLY TO YOUR DATAFRAME ----------
# Assuming your DataFrame is named df and has a 'LOCATION' column

# 1. Get unique locations
unique_locations = (
    df["LOCATION"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

location_to_coords = {}

# 2. Call Geocoding API once per unique location
for loc in unique_locations:
    lat, lng = geocode_with_google(loc)
    location_to_coords[loc] = (lat, lng)
    time.sleep(0.1)  # be a bit gentle with the API; adjust as needed

# 3. Map back to the dataframe as new columns
def lookup_lat(loc):
    loc = str(loc).strip()
    return location_to_coords.get(loc, (None, None))[0]

def lookup_lng(loc):
    loc = str(loc).strip()
    return location_to_coords.get(loc, (None, None))[1]

df["Latitude"] = df["LOCATION"].apply(lookup_lat)
df["Longitude"] = df["LOCATION"].apply(lookup_lng)

# 4. Quick check
df[["LOCATION", "Latitude", "Longitude"]].head()

                      LOCATION   Latitude  Longitude
0                   Adelphi Rd  38.994328 -76.960336
1              University Blvd  39.000374 -76.942387
2     7500 block of Girard Ave  38.981833 -76.930534
3  7500 block of Baltimore Ave  38.982465 -76.938124
4                   Adelphi Rd  38.994328 -76.960336

In [40]:
df.head()

,UMPD Case Number,Date Occurred,Report Date,Crime Type,Disposition,LOCATION,Crime_Category,Latitude,Longitude
0,2025-00000044,01/01/2025 01:10:00,01/01/2025 - 01:10,DWI/DUI,Arrest,Adelphi Rd,Substance/Impairment,38.994328,-76.960336
1,2025-00000055,01/01/2025 01:48:00,01/01/2025 - 01:48,DWI/DUI,Arrest,University Blvd,Substance/Impairment,39.000374,-76.942387
2,2025-00000056,01/01/2025 01:49:00,01/01/2025 - 01:49,Assist Other Agency,CBE,7500 block of Girard Ave,Public Safety/Suspicious,38.981833,-76.930534
3,2025-00000083,12/29/2024 21:00:00,01/01/2025 - 03:41,Dept Property Damage/Loss,CBE,7500 block of Baltimore Ave,Property,38.982465,-76.938124
4,2025-00000128,01/01/2025 05:45:00,01/01/2025 - 05:45,DWI/DUI,Arrest,Adelphi Rd,Substance/Impairment,38.994328,-76.960336

In [42]:
df.to_csv(f"crime_data_{year}.csv", index=False) #EXPORT TO CSV